# resource "aws_ecs_task_definition" "taskdef" {
#     family = "my-notification-service"
#     network_mode = "awsvpc"
#     cpu = 256
#     memory = 512

#    container_definitions = [
#     {
#       name = "my-notification-server"
#       image = "your_ecr_repository_url:latest"
#       essential = true
#       portMappings = [
#         {
#           containerPort = 80,
#           protocol = "tcp",
#         }
#       ]
#       memory = 3
#       cpu = 1
#     }
#    ]  
# }

